In [2]:
## Dependencies
# import os
import pandas as pd

## ID Municipios

In [2]:
ID_Municipios_2015 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/ID-Municipios-2015.csv", encoding="latin-1")
print(ID_Municipios_2015.shape)
ID_Municipios_2015.head()

(51, 2)

      ID    Municipio
0  19001      Abasolo
1  19002   Agualeguas
2  19003  Los Aldamas
3  19004      Allende
4  19005      Anáhuac

In [3]:
ID_Municipios_2018 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/ID-Municipios-2018.csv", encoding="latin-1")
print(ID_Municipios_2018.shape)
ID_Municipios_2018.head()

(51, 2)

      ID    Municipio
0  19001      Abasolo
1  19002   Agualeguas
2  19003  Los Aldamas
3  19004      Allende
4  19005      Anahuac

## Ayuntamientos 2015

In [4]:
ayuntamientos2015 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/CEENL-Ayuntamientos-2015.csv", encoding="latin-1")
print(ayuntamientos2015.shape)
ayuntamientos2015.head()

(6098, 34)

,Seccion,Casilla,Eleccion,Municipio,Distrito,Estatus,LN,Total,Partido Acción Nacional,Partido Revolucionario Institucional,...,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Combinación PRD PT,Votos Anulados
0,1,BASICA,Ayuntamiento,Abasolo,20,Acta contabilizada,410,336,10,74,...,0,0,0,0,0,0,0,0,0,3
1,1,CONTIGUA 1,Ayuntamiento,Abasolo,20,Acta contabilizada,410,335,7,101,...,0,0,0,0,0,0,0,0,5,0
2,2,BASICA,Ayuntamiento,Abasolo,20,Acta contabilizada,695,555,21,149,...,0,0,0,0,0,0,0,0,1,15
3,2,CONTIGUA 1,Ayuntamiento,Abasolo,20,Acta contabilizada,695,548,18,161,...,0,0,0,0,0,0,0,0,1,10
4,3,BASICA,Ayuntamiento,Agualeguas,22,Acta contabilizada,419,322,133,115,...,0,0,0,0,0,0,0,0,0,1

In [5]:
ayuntamientos2015.iloc[:,8:].columns

Index(['Partido Acción Nacional', 'Partido Revolucionario Institucional',
       'Partido de la Revolución Democrática', 'Partido del Trabajo',
       'Partido Verde Ecologista de México', 'Movimiento Ciudadano',
       'Nueva Alianza Partido Político Nacional', 'Partido Demócrata',
       'Partido Cruzada Ciudadana', 'MORENA',
       'Partido Humanista  Partido Político Nacional',
       'Partido Político Nacional  Encuentro Social',
       'Candidato Independiente', 'Combinación PRI PVEM NA PD',
       'Combinación PRI PVEM NA', 'Combinación PRI PVEM PD',
       'Combinación PRI NA PD', 'Combinación PVEM NA PD',
       'Combinación PRI PVEM', 'Combinación PRI NA', 'Combinación PRI PD',
       'Combinación PVEM NA', 'Combinación PVEM PD', 'Combinación NA PD',
       'Combinación PRD PT', 'Votos Anulados'],
      dtype='object')

In [6]:
votos_a2015 = ayuntamientos2015[['Municipio','Total','LN','Partido Acción Nacional',
    'Partido Revolucionario Institucional',
    'Partido de la Revolución Democrática',
    'Partido del Trabajo',
    'Partido Verde Ecologista de México',
    'Movimiento Ciudadano',
    'Nueva Alianza Partido Político Nacional',
    'Partido Demócrata',
    'Partido Cruzada Ciudadana',
    'MORENA',
    'Partido Humanista  Partido Político Nacional',
    'Partido Político Nacional  Encuentro Social',
    'Candidato Independiente',
    'Combinación PRI PVEM NA PD',
    'Combinación PRI PVEM NA',
    'Combinación PRI PVEM PD',
    'Combinación PRI NA PD',
    'Combinación PVEM NA PD',
    'Combinación PRI PVEM',
    'Combinación PRI NA',
    'Combinación PRI PD',
    'Combinación PVEM NA',
    'Combinación PVEM PD',
    'Combinación NA PD',
    'Combinación PRD PT']].groupby('Municipio').sum()

print(votos_a2015.shape)
votos_a2015.head()

(51, 27)

,Total,LN,Partido Acción Nacional,Partido Revolucionario Institucional,Partido de la Revolución Democrática,Partido del Trabajo,Partido Verde Ecologista de México,Movimiento Ciudadano,Nueva Alianza Partido Político Nacional,Partido Demócrata,...,Combinación PRI PVEM PD,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Combinación PRD PT
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1774,2210,56,485,554,15,121,486,0,0,...,0,0,0,0,0,0,0,0,0,7
Agualeguas,2792,3792,1202,742,0,0,816,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Allende,14662,24878,8078,5435,0,169,245,174,94,0,...,0,0,0,0,0,0,0,0,0,0
Anáhuac,9546,14047,3072,3531,0,300,86,34,119,0,...,0,0,0,0,0,0,0,0,0,0
Apodaca,193861,360935,57933,66613,3054,3692,8366,18320,5684,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
votos_a2015.rename({'LN': 'LNominal',
                    'Partido Acción Nacional': 'PAN',
                    'Partido Revolucionario Institucional': 'PRI',
                    'Partido de la Revolución Democrática': 'PRD',
                    'Partido del Trabajo': 'PT',
                    'Partido Verde Ecologista de México': 'PVEM',
                    'Movimiento Ciudadano': 'MC',
                    'Nueva Alianza Partido Político Nacional': 'NA',
                    'Partido Demócrata': 'PD',
                    'Partido Cruzada Ciudadana': 'PCD',
                    'Partido Humanista  Partido Político Nacional': 'PH',
                    'Partido Político Nacional  Encuentro Social': 'PES',
                    'Candidato Independiente': 'IND'}, axis=1, inplace=True)

In [8]:
votos_a2015.head()

,Total,LNominal,PAN,PRI,PRD,PT,PVEM,MC,NA,PD,...,Combinación PRI PVEM PD,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Combinación PRD PT
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1774,2210,56,485,554,15,121,486,0,0,...,0,0,0,0,0,0,0,0,0,7
Agualeguas,2792,3792,1202,742,0,0,816,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Allende,14662,24878,8078,5435,0,169,245,174,94,0,...,0,0,0,0,0,0,0,0,0,0
Anáhuac,9546,14047,3072,3531,0,300,86,34,119,0,...,0,0,0,0,0,0,0,0,0,0
Apodaca,193861,360935,57933,66613,3054,3692,8366,18320,5684,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
votos_a2015['PRI'] = votos_a2015['PRI'] + (votos_a2015['PVEM']*.6) + \
    votos_a2015['Combinación PRI PVEM NA PD'] + votos_a2015['Combinación PRI PVEM NA'] + \
    votos_a2015['Combinación PRI PVEM PD'] + votos_a2015['Combinación PRI NA PD'] + \
    votos_a2015['Combinación PVEM NA PD'] + votos_a2015['Combinación PRI PVEM'] + \
    votos_a2015['Combinación PRI NA'] + votos_a2015['Combinación PRI PD'] +  \
    votos_a2015['Combinación PVEM NA'] + votos_a2015['Combinación PVEM PD'] + \
    votos_a2015['Combinación NA PD'] 
votos_a2015['PRD'] = votos_a2015['PRD'] + (votos_a2015['PT']*1.01) + votos_a2015['Combinación PRD PT'] 

votos_a2015.drop('PVEM', axis=1, inplace=True)
votos_a2015.drop('PT', axis=1, inplace=True)

votos_a2015.head()

,Total,LNominal,PAN,PRI,PRD,MC,NA,PD,PCD,MORENA,...,Combinación PRI PVEM PD,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Combinación PRD PT
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1774,2210,56,557.6,576.15,486,0,0,0,22,...,0,0,0,0,0,0,0,0,0,7
Agualeguas,2792,3792,1202,1231.6,0.00,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Allende,14662,24878,8078,5582.0,170.69,174,94,0,0,158,...,0,0,0,0,0,0,0,0,0,0
Anáhuac,9546,14047,3072,3582.6,303.00,34,119,0,0,130,...,0,0,0,0,0,0,0,0,0,0
Apodaca,193861,360935,57933,71632.6,6782.92,18320,5684,0,0,3457,...,0,0,0,0,0,0,0,0,0,0

In [10]:
ganadores_a2015 = votos_a2015.iloc[:,2:].idxmax(axis=1)
ganadores_a2015.to_list()[0:5]

['PRD', 'PRI', 'PAN', 'PRI', 'PRI']

In [11]:
ganadores_a2015.value_counts()

PRI    22
PAN    18
PRD     7
MC      1
PES     1
NA      1
IND     1
dtype: int64

In [12]:
votos_a2015.insert(2, 'Ganador', ganadores_a2015)
print(votos_a2015.shape)
votos_a2015.head()

(51, 26)

,Total,LNominal,Ganador,PAN,PRI,PRD,MC,NA,PD,PCD,...,Combinación PRI PVEM PD,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Combinación PRD PT
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1774,2210,PRD,56,557.6,576.15,486,0,0,0,...,0,0,0,0,0,0,0,0,0,7
Agualeguas,2792,3792,PRI,1202,1231.6,0.00,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Allende,14662,24878,PAN,8078,5582.0,170.69,174,94,0,0,...,0,0,0,0,0,0,0,0,0,0
Anáhuac,9546,14047,PRI,3072,3582.6,303.00,34,119,0,0,...,0,0,0,0,0,0,0,0,0,0
Apodaca,193861,360935,PRI,57933,71632.6,6782.92,18320,5684,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
resumen_a2015 = votos_a2015[['PAN', 'PRI', 'MC', 'MORENA']]
resumen_a2015.insert(4,'Otro', votos_a2015.drop(['Total', 'LNominal', 'Ganador', 'PAN', 'PRI', 'MC', 'MORENA'], axis=1, inplace=False).max(axis=1))
resumen_a2015 = resumen_a2015.astype(int)
resumen_a2015.insert(0,'Ganador', votos_a2015['Ganador'])
resumen_a2015['Total'] = votos_a2015['Total']
resumen_a2015['LNominal'] = votos_a2015['LNominal']
resumen_a2015.head()

           Ganador    PAN    PRI     MC  MORENA   Otro   Total  LNominal
Municipio
Abasolo        PRD     56    557    486      22    576    1774      2210
Agualeguas     PRI   1202   1231      0       0      0    2792      3792
Allende        PAN   8078   5582    174     158    170   14662     24878
Anáhuac        PRI   3072   3582     34     130   2092    9546     14047
Apodaca        PRI  57933  71632  18320    3457  19629  193861    360935

In [14]:
resultados_a2015 = ID_Municipios_2015.merge(resumen_a2015, on='Municipio')
print(resultados_a2015.shape)
resultados_a2015

## Resultados Ayuntamientos 2015:
## http://computo2015oficial.ceenl.mx/eleccionc_1_M.html

(51, 10)

,ID,Municipio,Ganador,PAN,PRI,MC,MORENA,Otro,Total,LNominal
0,19001,Abasolo,PRD,56,557,486,22,576,1774,2210
1,19002,Agualeguas,PRI,1202,1231,0,0,0,2792,3792
2,19003,Los Aldamas,PRI,545,829,0,0,0,1501,2214
3,19004,Allende,PAN,8078,5582,174,158,170,14662,24878
4,19005,Anáhuac,PRI,3072,3582,34,130,2092,9546,14047
5,19006,Apodaca,PRI,57933,71632,18320,3457,19629,193861,360935
6,19007,Aramberri,PRI,3068,5813,16,0,317,9554,11719
7,19008,Bustamante,PAN,1029,816,0,23,763,2653,3238
8,19009,Cadereyta Jiménez,PRI,11425,17383,328,226,1204,36578,66345
9,19010,El Carmen,PRD,1837,2007,996,0,2021,7654,13425
10,19011,Cerralvo,PAN,2561,1671,0,0,0,4273,6323
11,19012,Ciénega de Flores,PRD,1397,2723,241,0,5443,12029,22577
12,19013,China,PAN,1898,1156,0,0,1325,6373,9425
13,19014,Dr. Arroyo,PRI,8482,11544,0,0,244,20819,26658
14,19015,Dr. Coss,PRI,716,881,0,0,86,1774,2713
15,19016,Dr. González,PRI,630,662,0,0,656,2014,3023
16,19017,Galeana,PRI,3850,9358,0,0,5290,20536,29781
17,19018,García,IND,7409,21045,1237,431,25557,61277,110470
18,19019,San Pedro Garza García,PAN,33433,10593,0,449,11260,65142,100475
19,19020,Gral. Bravo,PAN,1985,1888,0,0,0,3899,5558
20,19021,Gral. Escobedo,PRI,25285,56892,7632,0,25805,128412,251429
21,19022,Gral. Terán,PRI,3017,3033,0,0,1597,7947,12585
22,19023,Gral. Treviño,PAN,810,433,0,0,0,1256,1786
23,19024,Gral. Zaragoza,PRD,96,1717,0,0,2267,4146,4897
24,19025,Gral. Zuazua,PAN,7027,4551,0,690,1383,14784,29271
25,19026,Guadalupe,PAN,116267,107815,24207,5798,21107,307151,523886
26,19027,Los Herreras,PAN,1017,914,0,0,52,2010,2722
27,19047,Hidalgo,MC,1884,2059,2227,233,1271,8425,12237
28,19028,Higueras,PAN,520,471,0,0,99,1104,1341
29,19029,Hualahuises,PRI,1614,1862,0,0,388,4156,5874
30,19030,Iturbide,PRI,1156,1305,0,0,11,2515,2915
31,19031,Juárez,PES,18814,27654,2411,928,30182,86268,170059
32,19032,Lampazos de Naranjo,PAN,2280,1098,0,0,0,3428,4470
33,19033,Linares,PAN,20044,7651,177,0,5783,35206,60403
34,19034,Marín,PRI,837,1208,0,0,838,2972,4393
35,19035,Melchor Ocampo,NA,0,520,0,0,581,1107,1355
36,19036,Mier y Noriega,PRI,1667,2307,0,6,89,4248,5740
37,19037,Mina,PRI,84,2303,0,0,465,3482,4473
38,19038,Montemorelos,PRI,7067,12646,0,378,3142,27259,48142
39,19039,Monterrey,PRI,142832,169899,42014,8608,115773,539686,904720
40,19040,Parás,PAN,920,537,0,0,0,1465,1785
41,19041,Pesquería,PRI,1000,9719,165,64,1138,14812,25840
42,19042,Los Ramones,PRI,928,1785,0,7,101,3222,5221
43,19043,Rayones,PAN,1411,1381,0,0,0,2810,3143
44,19044,Sabinas Hidalgo,PAN,9966,6838,0,254,269,18072,26724
45,19045,Salinas Victoria,PRD,4769,5718,0,84,5926,17247,29618
46,19046,San Nicolás de los Garza,PAN,117780,44021,23803,4853,7353,223775,360641
47,19048,Santa Catarina,PAN,52096,23551,7444,1340,13356,108840,194766
48,19049,Santiago,PRI,5247,8415,884,116,4218,21300,34474
49,19050,Vallecillo,PRD,33,731,0,0,795,1583,2111
50,19051,Villaldama,PRD,1006,427,0,0,1029,2905,3630

## Ayuntamientos 2018

In [15]:
ayuntamientos2018 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/CEENL-Ayuntamientos-2018.csv", skiprows=5, encoding="latin-1",
                           names = ['CLAVE_CASILLA','CLAVE_ACTA','ID_ESTADO','ESTADO',
                                    'ID_MUNICIPIO','Municipio','SECCION','ID_CASILLA','TIPO_CASILLA','EXT_CONTIGUA',
                                    'UBICACION_CASILLA','TIPO_ACTA','TOTAL_BOLETAS_SOBRANTES','TOTAL_PERSONAS_VOTARON',
                                    'TOTAL_REP_PARTIDO_CI_VOTARON','TOTAL_VOTOS_SACADOS','PAN','PRI','PRD','PT',
                                    'PVEM','MC','NAPPN','MORENA','PES','RED','C_PRI_PVEM','C_PT_MORENA_PES',
                                    'C_PT_MORENA','C_PT_PES','C_MORENA_PES','CI_1','CI_2','CI_3','CI_4','CI_5','CI_6',
                                    'CNR','Votos Anulados','TOTAL_VOTOS_ASENTADO','Total','LNominal',
                                    'REPRESENTANTES_PP_CI','OBSERVACIONES','CONTABILIZADA','MECANISMOS_TRASLADO','SHA',
                                    'FECHA_HORA_ACOPIO','FECHA_HORA_CAPTURA','FECHA_HORA_VERIFICACION','ORIGEN',
                                    'DIGITALIZACION','TIPO_DOCUMENTO'])

print(ayuntamientos2018.shape)
ayuntamientos2018.head()

(6538, 53)

,CLAVE_CASILLA,CLAVE_ACTA,ID_ESTADO,ESTADO,ID_MUNICIPIO,Municipio,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,190001B0100,190001B01005,19,NUEVO LEON,1,Abasolo,1,1,B,NaN,...,NaN,1,F,NaN,NaN,04/07/2018 12:09:56,NaN,NaN,NaN,
1,190001C0201,190001C02015,19,NUEVO LEON,1,Abasolo,1,2,C,1.0,...,NaN,1,F,NaN,NaN,04/07/2018 12:11:31,NaN,NaN,NaN,
2,190002B0100,190002B01005,19,NUEVO LEON,1,Abasolo,2,1,B,NaN,...,NaN,1,F,NaN,NaN,04/07/2018 12:12:38,NaN,NaN,NaN,
3,190002C0201,190002C02015,19,NUEVO LEON,1,Abasolo,2,2,C,1.0,...,NaN,1,F,NaN,NaN,04/07/2018 12:14:12,NaN,NaN,NaN,
4,190003B0100,190003B01005,19,NUEVO LEON,2,Agualeguas,3,1,B,NaN,...,NaN,1,F,NaN,NaN,04/07/2018 10:53:05,NaN,NaN,NaN,

In [16]:
ayuntamientos2018.iloc[:,15:40].columns

Index(['TOTAL_VOTOS_SACADOS', 'PAN', 'PRI', 'PRD', 'PT', 'PVEM', 'MC', 'NAPPN',
       'MORENA', 'PES', 'RED', 'C_PRI_PVEM', 'C_PT_MORENA_PES', 'C_PT_MORENA',
       'C_PT_PES', 'C_MORENA_PES', 'CI_1', 'CI_2', 'CI_3', 'CI_4', 'CI_5',
       'CI_6', 'CNR', 'Votos Anulados', 'TOTAL_VOTOS_ASENTADO'],
      dtype='object')

In [17]:
votos_a2018 = ayuntamientos2018[['Municipio','Total', 'LNominal', 'PAN', 'PRI', 'PRD', 'PT', 'PVEM', 'MC', 'NAPPN',
       'MORENA', 'PES', 'RED', 'C_PRI_PVEM', 'C_PT_MORENA_PES', 'C_PT_MORENA', 'C_PT_PES', 'C_MORENA_PES',
        'CI_1', 'CI_2', 'CI_3', 'CI_4', 'CI_5', 'CI_6', 'CNR', 'Votos Anulados']].groupby('Municipio').sum()

print(votos_a2018.shape)
votos_a2018.head()

(51, 25)

,Total,LNominal,PAN,PRI,PRD,PT,PVEM,MC,NAPPN,MORENA,...,C_PT_PES,C_MORENA_PES,CI_1,CI_2,CI_3,CI_4,CI_5,CI_6,CNR,Votos Anulados
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1734,2288,119,440,31,33,18,436,34,23,...,0,0,438,0,0,0,0,0,1,54
Agualeguas,2938,3965,1216,1074,0,0,1,601,12,0,...,0,0,0,0,0,0,0,0,1,33
Allende,14358,27284,4633,4764,0,431,90,2039,1038,833,...,4,5,0,0,0,0,0,0,1,376
Anahuac,9218,14525,1582,3280,32,62,56,851,25,240,...,0,0,2781,0,0,0,0,0,0,287
Apodaca,219581,403094,50330,69818,1480,5883,5958,10756,4914,41643,...,45,186,20989,0,0,0,0,0,64,4059

In [18]:
votos_a2018.rename({'NAPPN': 'NA',
                    'CI_1': 'IND-1',
                    'CI_2': 'IND-2'}, axis=1, inplace=True)

In [19]:
votos_a2018['PRI'] = votos_a2018['PRI'] + (votos_a2018['PVEM']*.74) + votos_a2018['C_PRI_PVEM']
votos_a2018['MORENA'] = votos_a2018['MORENA'] + (votos_a2018['PT']*.75) + (votos_a2018['PES']*.74)

votos_a2018.drop('PVEM', axis=1, inplace=True)
votos_a2018.drop('PT', axis=1, inplace=True)
votos_a2018.drop('RED', axis=1, inplace=True)

votos_a2018.head()

,Total,LNominal,PAN,PRI,PRD,MC,NA,MORENA,PES,C_PRI_PVEM,...,C_PT_PES,C_MORENA_PES,IND-1,IND-2,CI_3,CI_4,CI_5,CI_6,CNR,Votos Anulados
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1734,2288,119,455.32,31,436,34,51.45,5,2,...,0,0,438,0,0,0,0,0,1,54
Agualeguas,2938,3965,1216,1074.74,0,601,12,0.00,0,0,...,0,0,0,0,0,0,0,0,1,33
Allende,14358,27284,4633,4830.60,0,2039,1038,1213.23,77,0,...,4,5,0,0,0,0,0,0,1,376
Anahuac,9218,14525,1582,3321.44,32,851,25,292.42,8,0,...,0,0,2781,0,0,0,0,0,0,287
Apodaca,219581,403094,50330,74226.92,1480,10756,4914,47793.51,2349,0,...,45,186,20989,0,0,0,0,0,64,4059

In [20]:
ganadores_a2018 = votos_a2018.iloc[:,2:].idxmax(axis=1)
ganadores_a2018.to_list()[0:5]

['PRI', 'PAN', 'PRI', 'PRI', 'PRI']

In [21]:
ganadores_a2018.value_counts()

PRI       22
PAN       16
NA         4
IND-1      3
MORENA     3
MC         1
IND-2      1
PRD        1
dtype: int64

In [22]:
votos_a2018.insert(2, 'Ganador', ganadores_a2018)
print(votos_a2018.shape)
votos_a2018.head()

(51, 23)

,Total,LNominal,Ganador,PAN,PRI,PRD,MC,NA,MORENA,PES,...,C_PT_PES,C_MORENA_PES,IND-1,IND-2,CI_3,CI_4,CI_5,CI_6,CNR,Votos Anulados
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,1734,2288,PRI,119,455.32,31,436,34,51.45,5,...,0,0,438,0,0,0,0,0,1,54
Agualeguas,2938,3965,PAN,1216,1074.74,0,601,12,0.00,0,...,0,0,0,0,0,0,0,0,1,33
Allende,14358,27284,PRI,4633,4830.60,0,2039,1038,1213.23,77,...,4,5,0,0,0,0,0,0,1,376
Anahuac,9218,14525,PRI,1582,3321.44,32,851,25,292.42,8,...,0,0,2781,0,0,0,0,0,0,287
Apodaca,219581,403094,PRI,50330,74226.92,1480,10756,4914,47793.51,2349,...,45,186,20989,0,0,0,0,0,64,4059

In [23]:
resumen_a2018 = votos_a2018[['PAN', 'PRI', 'MC', 'MORENA']]
resumen_a2018.insert(4,'Otro', votos_a2018.drop(['Total', 'LNominal', 'Ganador', 'PAN', 'PRI', 'MC', 'MORENA'], axis=1, inplace=False).max(axis=1))
resumen_a2018 = resumen_a2018.astype(int)
resumen_a2018.insert(0,'Ganador', votos_a2018['Ganador'])
resumen_a2018['Total'] = votos_a2018['Total']
resumen_a2018['LNominal'] = votos_a2018['LNominal']
resumen_a2018.head()

           Ganador    PAN    PRI     MC  MORENA   Otro   Total  LNominal
Municipio
Abasolo        PRI    119    455    436      51    438    1734      2288
Agualeguas     PAN   1216   1074    601       0     33    2938      3965
Allende        PRI   4633   4830   2039    1213   1038   14358     27284
Anahuac        PRI   1582   3321    851     292   2781    9218     14525
Apodaca        PRI  50330  74226  10756   47793  20989  219581    403094

In [24]:
resultados_a2018 = ID_Municipios_2018.merge(resumen_a2018, on='Municipio')
print(resultados_a2018.shape)
resultados_a2018

## Resultados Ayuntamientos 2018:
## https://computo2018.ceenl.mx/GC01M04.htm

(51, 10)

,ID,Municipio,Ganador,PAN,PRI,MC,MORENA,Otro,Total,LNominal
0,19001,Abasolo,PRI,119,455,436,51,438,1734,2288
1,19002,Agualeguas,PAN,1216,1074,601,0,33,2938,3965
2,19003,Los Aldamas,NA,626,34,0,0,686,1369,2160
3,19004,Allende,PRI,4633,4830,2039,1213,1038,14358,27284
4,19005,Anahuac,PRI,1582,3321,851,292,2781,9218,14525
5,19006,Apodaca,PRI,50330,74226,10756,47793,20989,219581,403094
6,19007,Aramberri,PRI,3611,4554,12,150,964,9696,12010
7,19008,Bustamante,NA,1050,135,0,30,1360,2632,3293
8,19009,Cadereyta Jimenez,PRI,3973,10809,950,9620,4312,39379,77542
9,19010,El Carmen,PRI,618,4867,181,3048,690,10642,22227
10,19011,Cerralvo,PAN,2667,140,23,474,633,4114,6507
11,19012,Cienega de Flores,IND-1,777,3135,482,1454,5872,14891,31320
12,19013,China,NA,1534,1159,0,0,1765,6326,9483
13,19014,Dr. Arroyo,PRI,7553,11419,21,308,1180,21635,28105
14,19015,Dr. Coss,PRI,437,670,0,0,613,1784,2717
15,19016,Dr. Gonzalez,PRI,284,502,56,335,368,2187,3153
16,19017,Galeana,PRI,725,9789,206,3029,2751,19355,30138
17,19018,Garcia,IND-1,7990,7916,3560,15841,24529,66089,150560
18,19019,San Pedro Garza Garcia,IND-2,25169,2907,0,2804,32326,68945,103718
19,19020,Gral. Bravo,PAN,1836,135,0,65,1530,3759,5665
20,19021,Gral. Escobedo,PRI,33814,61123,5240,24375,6460,140698,292794
21,19022,Gral. Teran,PRI,306,3057,1004,625,1104,8029,13007
22,19023,Gral. Trevino,PAN,739,186,0,27,479,1462,1892
23,19024,Gral. Zaragoza,MORENA,48,1055,1,1170,1164,4046,4977
24,19025,Gral. Zuazua,PRI,3877,5599,737,3334,1011,17405,37387
25,19026,Guadalupe,PAN,83318,76764,12398,43358,53690,305371,538211
26,19027,Los Herreras,PAN,639,587,27,121,327,1967,2686
27,19047,Hidalgo,PRI,1095,1663,533,427,918,8827,12798
28,19028,Higueras,PRD,336,94,0,4,596,1174,1438
29,19029,Hualahuises,PRI,665,2457,0,60,653,4256,6147
30,19030,Iturbide,PRI,40,1861,0,63,341,2630,3013
31,19031,Juarez,PRI,8585,29451,6120,13723,26206,96578,209923
32,19032,Lampazos de Naranjo,PAN,2541,930,0,25,65,3582,4754
33,19033,Linares,PAN,15518,9201,244,2495,4434,33859,63409
34,19034,Marin,PAN,1344,1263,24,32,86,3275,4575
35,19035,Melchor Ocampo,NA,19,2,0,405,812,1417,1698
36,19036,Mier y Noriega,IND-1,42,2061,1,401,2159,4828,6215
37,19037,Mina,PRI,46,1794,120,32,451,3523,4709
38,19038,Montemorelos,MORENA,3091,9319,934,9591,1191,26970,51570
39,19039,Monterrey,PRI,153035,182941,20885,85568,25809,524377,923402
40,19040,Paras,PAN,847,628,0,9,29,1529,1851
41,19041,Pesqueria,PRI,1128,9865,508,3539,4095,20921,50678
42,19042,Los Ramones,PAN,1026,736,3,26,922,3084,5290
43,19043,Rayones,PAN,1751,880,0,18,52,2793,3277
44,19044,Sabinas Hidalgo,PAN,9410,3904,587,1410,381,16728,27700
45,19045,Salinas Victoria,PAN,9980,5949,613,1897,985,20876,39283
46,19046,San Nicolas de los Garza,PAN,107265,24882,12791,33803,13080,221915,365168
47,19048,Santa Catarina,PAN,60390,10333,4268,13195,19571,116464,212885
48,19049,Santiago,PRI,7789,9225,892,2098,955,22679,37516
49,19050,Vallecillo,MORENA,26,302,232,391,291,1736,2287
50,19051,Villaldama,MC,1201,30,1237,212,93,2936,3672

## Ayuntamientos 2021

In [25]:
ayuntamientos2021 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/CEENL-Ayuntamientos-2021.csv", skiprows=5, encoding="latin-1",
                           names = ['CLAVE_CASILLA','CLAVE_ACTA','ID_ESTADO','ESTADO','ID_MUNICIPIO','Municipio',
                                    'SECCION','ID_CASILLA','TIPO_CASILLA','EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA',
                                    'TOTAL_BOLETAS_SOBRANTES','TOTAL_PERSONAS_VOTARON','TOTAL_REP_PARTIDO_CI_VOTARON',
                                    'TOTAL_VOTOS_SACADOS','PAN','PRI','PRD','PVEM','PT','MC','MORENA','PANAL','PES',
                                    'RSP','FXM','CI_1','CI_2','C_PRI_PRD','C_PVEM_PT_MORENA_PANAL','C_PVEM_PT_MORENA',
                                    'C_PVEM_PT_PANAL','C_PVEM_MORENA_PANAL','C_PT_MORENA_PANAL','C_PVEM_PT',
                                    'C_PVEM_MORENA','C_PVEM_PANAL','C_PT_MORENA','C_PT_PANAL','C_MORENA_PANAL',
                                    'NO_REGISTRADOS','NULOS','TOTAL_VOTOS_ASENTADO','Total',
                                    'LNominal','REPRESENTANTES_PP_CI','OBSERVACIONES','CONTABILIZADA',
                                    'MECANISMOS_TRASLADO','SHA','FECHA_HORA_ACOPIO','FECHA_HORA_CAPTURA',
                                    'FECHA_HORA_VERIFICACION','ORIGEN','DIGITALIZACION','TIPO_DOCUMENTO',])

print(ayuntamientos2021.shape)
ayuntamientos2021.head()

(7003, 57)

,CLAVE_CASILLA,CLAVE_ACTA,ID_ESTADO,ESTADO,ID_MUNICIPIO,Municipio,SECCION,ID_CASILLA,TIPO_CASILLA,EXT_CONTIGUA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,190001B0100,190001B01004,19,NUEVO LEON,1,Abasolo,1,1,B,0,...,Por CME,1,D,NaN,NaN,09/06/2021 08:26:41,NaN,NaN,NaN,-
1,190001C0100,190001C01004,19,NUEVO LEON,1,Abasolo,1,1,C,0,...,Por CME,1,D,NaN,NaN,09/06/2021 09:45:25,NaN,NaN,NaN,-
2,190002B0100,190002B01004,19,NUEVO LEON,1,Abasolo,2,1,B,0,...,Por CME,1,D,NaN,NaN,09/06/2021 11:00:20,NaN,NaN,NaN,-
3,190002C0100,190002C01004,19,NUEVO LEON,1,Abasolo,2,1,C,0,...,Por CME,1,D,NaN,NaN,09/06/2021 11:58:10,NaN,NaN,NaN,-
4,190003B0100,190003B01004,19,NUEVO LEON,2,Agualeguas,3,1,B,0,...,Por CME,1,D,NaN,NaN,09/06/2021 09:06:21,NaN,NaN,NaN,-

In [26]:
ayuntamientos2021.iloc[:,15:44].columns

Index(['TOTAL_VOTOS_SACADOS', 'PAN', 'PRI', 'PRD', 'PVEM', 'PT', 'MC',
       'MORENA', 'PANAL', 'PES', 'RSP', 'FXM', 'CI_1', 'CI_2', 'C_PRI_PRD',
       'C_PVEM_PT_MORENA_PANAL', 'C_PVEM_PT_MORENA', 'C_PVEM_PT_PANAL',
       'C_PVEM_MORENA_PANAL', 'C_PT_MORENA_PANAL', 'C_PVEM_PT',
       'C_PVEM_MORENA', 'C_PVEM_PANAL', 'C_PT_MORENA', 'C_PT_PANAL',
       'C_MORENA_PANAL', 'NO_REGISTRADOS', 'NULOS', 'TOTAL_VOTOS_ASENTADO'],
      dtype='object')

In [27]:
votos_a2021 = ayuntamientos2021[['Municipio','Total', 'LNominal', 'PAN', 'PRI', 'PRD', 'PVEM', 'PT', 'MC',
    'MORENA', 'PANAL', 'PES', 'RSP', 'FXM', 'CI_1', 'CI_2', 'C_PRI_PRD', 'C_PVEM_PT_MORENA_PANAL',
    'C_PVEM_PT_MORENA', 'C_PVEM_PT_PANAL', 'C_PVEM_MORENA_PANAL', 'C_PT_MORENA_PANAL', 'C_PVEM_PT',
    'C_PVEM_MORENA', 'C_PVEM_PANAL', 'C_PT_MORENA', 'C_PT_PANAL', 'C_MORENA_PANAL',
    'NO_REGISTRADOS', 'NULOS']].groupby('Municipio').sum()

print(votos_a2021.shape)
votos_a2021.head()

(51, 29)

,Total,LNominal,PAN,PRI,PRD,PVEM,PT,MC,MORENA,PANAL,...,C_PVEM_MORENA_PANAL,C_PT_MORENA_PANAL,C_PVEM_PT,C_PVEM_MORENA,C_PVEM_PANAL,C_PT_MORENA,C_PT_PANAL,C_MORENA_PANAL,NO_REGISTRADOS,NULOS
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,2018,2512,544,31,0,514,123,426,0,0,...,0,0,0,0,0,0,0,0,0,21
Agualeguas,2866,4147,1795,128,4,2,0,806,80,0,...,0,0,0,0,0,0,0,0,0,47
Allende,13205,28919,3417,5947,28,145,124,1251,618,207,...,0,1,0,3,2,1,3,4,1,232
Anahuac,8964,14822,635,4775,0,51,0,91,442,0,...,0,0,0,0,0,0,0,0,1,229
Apodaca,220494,440894,22136,141171,3525,1863,1722,21375,20008,895,...,25,23,34,94,10,147,18,30,57,3336

In [28]:
votos_a2021.rename({'PANAL': 'NA',
                    'CI_1': 'IND'}, axis=1, inplace=True)

In [29]:
votos_a2021['PRI'] = votos_a2021['PRI'] + votos_a2021['PRD'] + votos_a2021['C_PRI_PRD']
votos_a2021['MORENA'] = votos_a2021['MORENA'] + votos_a2021['PT'] + \
    votos_a2021['C_PVEM_PT_MORENA_PANAL'] + votos_a2021['C_PVEM_PT_MORENA'] + votos_a2021['C_PVEM_MORENA_PANAL'] + \
    votos_a2021['C_PVEM_PT_PANAL'] + votos_a2021['C_PT_MORENA_PANAL'] + votos_a2021['C_PVEM_PT'] + \
    votos_a2021['C_PVEM_MORENA'] + votos_a2021['C_PVEM_PANAL'] + votos_a2021['C_PT_MORENA'] + \
    votos_a2021['C_PT_PANAL'] + votos_a2021['C_MORENA_PANAL'] + (votos_a2021['PVEM']*.4) + (votos_a2021['NA']*.9)

votos_a2021.drop('PRD', axis=1, inplace=True)
votos_a2021.drop('PT', axis=1, inplace=True)

votos_a2021.head()

,Total,LNominal,PAN,PRI,PVEM,MC,MORENA,NA,PES,RSP,...,C_PVEM_MORENA_PANAL,C_PT_MORENA_PANAL,C_PVEM_PT,C_PVEM_MORENA,C_PVEM_PANAL,C_PT_MORENA,C_PT_PANAL,C_MORENA_PANAL,NO_REGISTRADOS,NULOS
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,2018,2512,544,31,514,426,328.6,0,0,0,...,0,0,0,0,0,0,0,0,0,21
Agualeguas,2866,4147,1795,133,2,806,80.8,0,0,3,...,0,0,0,0,0,0,0,0,0,47
Allende,13205,28919,3417,5995,145,1251,1020.3,207,0,1181,...,0,1,0,3,2,1,3,4,1,232
Anahuac,8964,14822,635,4775,51,91,462.4,0,0,0,...,0,0,0,0,0,0,0,0,1,229
Apodaca,220494,440894,22136,145705,1863,21375,24029.7,895,1107,628,...,25,23,34,94,10,147,18,30,57,3336

In [30]:
ganadores_a2021 = votos_a2021.iloc[:,2:].idxmax(axis=1)
ganadores_a2021.to_list()[0:5]

['PAN', 'PAN', 'PRI', 'PRI', 'PRI']

In [31]:
ganadores_a2021.value_counts()

PAN       16
PRI       13
MORENA     8
MC         6
PVEM       4
NA         2
IND        2
dtype: int64

In [32]:
votos_a2021.insert(1, 'Ganador', ganadores_a2021)
print(votos_a2021.shape)
votos_a2021.head()

(51, 28)

,Total,Ganador,LNominal,PAN,PRI,PVEM,MC,MORENA,NA,PES,...,C_PVEM_MORENA_PANAL,C_PT_MORENA_PANAL,C_PVEM_PT,C_PVEM_MORENA,C_PVEM_PANAL,C_PT_MORENA,C_PT_PANAL,C_MORENA_PANAL,NO_REGISTRADOS,NULOS
Municipio,,,,,,,,,,,,,,,,,,,,,
Abasolo,2018,PAN,2512,544,31,514,426,328.6,0,0,...,0,0,0,0,0,0,0,0,0,21
Agualeguas,2866,PAN,4147,1795,133,2,806,80.8,0,0,...,0,0,0,0,0,0,0,0,0,47
Allende,13205,PRI,28919,3417,5995,145,1251,1020.3,207,0,...,0,1,0,3,2,1,3,4,1,232
Anahuac,8964,PRI,14822,635,4775,51,91,462.4,0,0,...,0,0,0,0,0,0,0,0,1,229
Apodaca,220494,PRI,440894,22136,145705,1863,21375,24029.7,895,1107,...,25,23,34,94,10,147,18,30,57,3336

In [33]:
resumen_a2021 = votos_a2021[['PAN', 'PRI', 'MC', 'MORENA']]
resumen_a2021.insert(4,'Otro', votos_a2021.drop(['Total', 'LNominal', 'Ganador', 'PAN', 'PRI', 'MC', 'MORENA'], axis=1, inplace=False).max(axis=1))
resumen_a2021 = resumen_a2021.astype(int)
resumen_a2021.insert(0,'Ganador', votos_a2021['Ganador'])
resumen_a2021['Total'] = votos_a2021['Total']
resumen_a2021['LNominal'] = votos_a2021['LNominal']
resumen_a2021.head()

           Ganador    PAN     PRI     MC  MORENA  Otro   Total  LNominal
Municipio
Abasolo        PAN    544      31    426     328   514    2018      2512
Agualeguas     PAN   1795     133    806      80    47    2866      4147
Allende        PRI   3417    5995   1251    1020  1181   13205     28919
Anahuac        PRI    635    4775     91     462  2740    8964     14822
Apodaca        PRI  22136  145705  21375   24029  3336  220494    440894

In [34]:
resultados_a2021 = ID_Municipios_2018.merge(resumen_a2021, on='Municipio')
print(resultados_a2021.shape)
resultados_a2021

## Resultados Ayuntamientos 2021:
## https://computos2021.ceenl.mx/GC01M12.htm

(51, 10)

,ID,Municipio,Ganador,PAN,PRI,MC,MORENA,Otro,Total,LNominal
0,19001,Abasolo,PAN,544,31,426,328,514,2018,2512
1,19002,Agualeguas,PAN,1795,133,806,80,47,2866,4147
2,19003,Los Aldamas,MC,6,583,647,75,66,1363,2076
3,19004,Allende,PRI,3417,5995,1251,1020,1181,13205,28919
4,19005,Anahuac,PRI,635,4775,91,462,2740,8964,14822
5,19006,Apodaca,PRI,22136,145705,21375,24029,3336,220494,440894
6,19007,Aramberri,PRI,3457,5085,22,1264,216,10057,12646
7,19008,Bustamante,PAN,913,584,15,134,834,2653,3354
8,19009,Cadereyta Jimenez,PAN,15394,9430,1656,4735,3977,38107,85414
9,19010,El Carmen,PAN,3850,1391,1002,3702,2527,12154,32600
10,19011,Cerralvo,PAN,2333,236,51,1604,71,4313,6900
11,19012,Cienega de Flores,PVEM,4443,1680,580,3801,5812,15168,39601
12,19013,China,MORENA,82,1745,145,2153,2040,6660,9977
13,19014,Dr. Arroyo,PRI,1054,13188,348,6671,504,22052,29832
14,19015,Dr. Coss,NA,83,779,9,752,833,1788,2725
15,19016,Dr. Gonzalez,MORENA,222,912,25,1073,510,2354,3273
16,19017,Galeana,PRI,2481,8842,301,3293,6999,19670,31230
17,19018,Garcia,IND,8010,8071,10274,12434,17196,72577,199018
18,19019,San Pedro Garza Garcia,IND,24300,2303,2018,1634,41862,73312,107652
19,19020,Gral. Bravo,PAN,1914,1720,14,36,58,3758,5852
20,19021,Gral. Escobedo,MORENA,36911,24864,28827,38543,5194,137607,321812
21,19022,Gral. Teran,MC,0,3063,3235,434,640,7630,13304
22,19023,Gral. Trevino,PAN,893,602,0,12,14,1523,2097
23,19024,Gral. Zaragoza,MORENA,327,1855,0,2014,74,4294,5463
24,19025,Gral. Zuazua,MORENA,3052,3583,1343,5331,4844,19811,46179
25,19026,Guadalupe,PRI,83348,86825,48502,55614,8490,290084,551656
26,19027,Los Herreras,PVEM,209,718,81,491,877,2086,2902
27,19047,Hidalgo,MC,1206,967,2016,567,1738,8154,13163
28,19028,Higueras,PAN,752,464,0,6,12,1236,1475
29,19029,Hualahuises,PRI,70,2035,0,87,1985,4280,6307
30,19030,Iturbide,PRI,1238,1578,0,12,27,2856,3243
31,19031,Juarez,PRI,21984,37317,20247,15521,2470,100442,251782
32,19032,Lampazos de Naranjo,PAN,2672,132,108,708,47,3677,4921
33,19033,Linares,PAN,9921,5448,2671,5442,6480,31357,66567
34,19034,Marin,PVEM,594,306,0,903,2234,3187,4984
35,19035,Melchor Ocampo,MORENA,392,9,110,830,805,1476,1937
36,19036,Mier y Noriega,MORENA,1287,371,843,1562,1192,4880,6482
37,19037,Mina,PRI,282,1955,0,423,1053,3494,4944
38,19038,Montemorelos,PRI,3618,9158,3820,6001,934,24640,54852
39,19039,Monterrey,MC,43211,170958,254541,52237,9144,538941,963019
40,19040,Paras,PAN,852,729,0,24,21,1630,2008
41,19041,Pesqueria,PAN,10904,3256,1858,6108,883,23321,70795
42,19042,Los Ramones,NA,1174,362,0,1151,1255,2987,5372
43,19043,Rayones,PAN,1775,204,17,363,48,2426,3110
44,19044,Sabinas Hidalgo,MC,4990,801,8400,1012,1229,16814,29104
45,19045,Salinas Victoria,MC,6247,4193,8136,2169,715,22592,48612
46,19046,San Nicolas de los Garza,PAN,118241,21684,30999,27569,3209,207267,367121
47,19048,Santa Catarina,PAN,54666,11186,16821,14772,2223,104951,225939
48,19049,Santiago,PRI,3707,9263,713,4081,6296,25156,40354
49,19050,Vallecillo,MORENA,38,679,0,935,20,1682,2334
50,19051,Villaldama,PVEM,889,85,984,449,1086,3101,3883

## Gubernatura 2015

In [35]:
gubernatura2015 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/CEENL-Gubernatura-2015.csv", encoding="latin-1")
print(gubernatura2015.shape)
gubernatura2015.head()

(6098, 33)

,Seccion,Casilla,Eleccion,Municipio,Distrito,Estatus,LN,Total,Partido Acción Nacional,Partido Revolucionario Institucional,...,Combinación PRI PVEM PD,Combinación PRI NA PD,Combinación PVEM NA PD,Combinación PRI PVEM,Combinación PRI NA,Combinación PRI PD,Combinación PVEM NA,Combinación PVEM PD,Combinación NA PD,Votos Anulados
0,1,BASICA,Gobernador,Abasolo,20,Acta contabilizada,410,336,47,87,...,0,0,0,0,0,0,0,0,0,5
1,1,CONTIGUA 1,Gobernador,Abasolo,20,Acta contabilizada,410,335,24,127,...,0,0,0,0,0,0,1,0,0,8
2,2,BASICA,Gobernador,Abasolo,20,Acta contabilizada,695,555,65,181,...,0,0,0,0,0,1,0,0,0,16
3,2,CONTIGUA 1,Gobernador,Abasolo,20,Acta contabilizada,695,531,71,176,...,0,0,0,1,0,0,0,0,0,0
4,3,BASICA,Gobernador,Agualeguas,22,Acta contabilizada,419,325,133,99,...,0,0,0,2,0,0,0,0,0,4

In [36]:
gubernatura2015.iloc[:,8:].columns
gubernatura2015.iloc[:,7:].sum(axis=0)

Total                                           2090280
Partido Acción Nacional                          466543
Partido Revolucionario Institucional             462778
Partido de la Revolución Democrática              10104
Partido del Trabajo                               16132
Partido Verde Ecologista de México                15854
Movimiento Ciudadano                              10881
Nueva Alianza Partido Político Nacional           11600
Partido Demócrata                                  1093
Partido Cruzada Ciudadana                          1580
MORENA                                             6536
Partido Humanista  Partido Político Nacional       7617
Partido Político Nacional  Encuentro Social        6679
Candidato Independiente                         1020552
Combinación PRI PVEM NA PD                         1069
Combinación PRI PVEM NA                            1084
Combinación PRI PVEM PD                              79
Combinación PRI NA PD                                86
Combinación PVEM NA PD                               43
Combinación PRI PVEM                               3220
Combinación PRI NA                                 1298
Combinación PRI PD                                  148
Combinación PVEM NA                                 197
Combinación PVEM PD                                  21
Combinación NA PD                                    74
Votos Anulados                                    45012
dtype: int64

In [37]:
votos_g2015 = gubernatura2015[['Municipio','Total','Partido Acción Nacional', 'Partido Revolucionario Institucional',
       'Partido de la Revolución Democrática', 'Partido del Trabajo',
       'Partido Verde Ecologista de México', 'Movimiento Ciudadano',
       'Nueva Alianza Partido Político Nacional', 'Partido Demócrata',
       'Partido Cruzada Ciudadana', 'MORENA',
       'Partido Humanista  Partido Político Nacional',
       'Partido Político Nacional  Encuentro Social',
       'Candidato Independiente', 
       'Votos Anulados']].groupby('Municipio').sum()

print(votos_g2015.shape)
votos_g2015.head()

(51, 15)

,Total,Partido Acción Nacional,Partido Revolucionario Institucional,Partido de la Revolución Democrática,Partido del Trabajo,Partido Verde Ecologista de México,Movimiento Ciudadano,Nueva Alianza Partido Político Nacional,Partido Demócrata,Partido Cruzada Ciudadana,MORENA,Partido Humanista Partido Político Nacional,Partido Político Nacional Encuentro Social,Candidato Independiente,Votos Anulados
Municipio,,,,,,,,,,,,,,,
Abasolo,1757,207,571,203,7,31,82,12,1,0,10,3,1,597,29
Agualeguas,2755,1117,741,0,2,529,2,4,3,2,0,1,1,287,38
Allende,14762,4253,3961,15,67,78,32,31,7,7,48,17,6,5721,491
Anáhuac,9528,3321,2895,8,118,40,15,42,6,4,34,903,2,1903,233
Apodaca,195274,38041,40402,755,937,1241,1094,815,74,158,642,506,335,106918,3086

In [38]:
votos_g2015.rename({'Partido Acción Nacional': 'PAN',
                    'Partido Revolucionario Institucional': 'PRI',
                    'Partido de la Revolución Democrática': 'PRD',
                    'Partido del Trabajo': 'PT',
                    'Partido Verde Ecologista de México': 'PVEM',
                    'Movimiento Ciudadano': 'MC',
                    'Nueva Alianza Partido Político Nacional': 'NA',
                    'Partido Demócrata': 'PD',
                    'Partido Cruzada Ciudadana': 'PCD',
                    'Partido Humanista  Partido Político Nacional': 'PH',
                    'Partido Político Nacional  Encuentro Social': 'PES',
                    'Candidato Independiente': 'IND'}, axis=1, inplace=True)

In [39]:
ganadores_g2015 = votos_g2015.iloc[:,1:].idxmax(axis=1)
ganadores_g2015.to_list()[0:5]

['IND', 'PAN', 'IND', 'PAN', 'IND']

In [40]:
ganadores_g2015.value_counts()

IND    22
PRI    17
PAN    12
dtype: int64

In [41]:
votos_g2015.insert(1, 'Ganador', ganadores_g2015)
print(votos_g2015.shape)
votos_g2015.head()

(51, 16)

,Total,Ganador,PAN,PRI,PRD,PT,PVEM,MC,NA,PD,PCD,MORENA,PH,PES,IND,Votos Anulados
Municipio,,,,,,,,,,,,,,,,
Abasolo,1757,IND,207,571,203,7,31,82,12,1,0,10,3,1,597,29
Agualeguas,2755,PAN,1117,741,0,2,529,2,4,3,2,0,1,1,287,38
Allende,14762,IND,4253,3961,15,67,78,32,31,7,7,48,17,6,5721,491
Anáhuac,9528,PAN,3321,2895,8,118,40,15,42,6,4,34,903,2,1903,233
Apodaca,195274,IND,38041,40402,755,937,1241,1094,815,74,158,642,506,335,106918,3086

In [42]:
resultados_g2015 = ID_Municipios_2015.merge(votos_g2015, on='Municipio')
print(resultados_g2015.shape)
resultados_g2015

(51, 18)

,ID,Municipio,Total,Ganador,PAN,PRI,PRD,PT,PVEM,MC,NA,PD,PCD,MORENA,PH,PES,IND,Votos Anulados
0,19001,Abasolo,1757,IND,207,571,203,7,31,82,12,1,0,10,3,1,597,29
1,19002,Agualeguas,2755,PAN,1117,741,0,2,529,2,4,3,2,0,1,1,287,38
2,19003,Los Aldamas,1507,PRI,547,689,1,3,148,2,4,0,0,1,1,0,90,19
3,19004,Allende,14762,IND,4253,3961,15,67,78,32,31,7,7,48,17,6,5721,491
4,19005,Anáhuac,9528,PAN,3321,2895,8,118,40,15,42,6,4,34,903,2,1903,233
5,19006,Apodaca,195274,IND,38041,40402,755,937,1241,1094,815,74,158,642,506,335,106918,3086
6,19007,Aramberri,9558,PRI,2081,4978,9,19,5,6,12,5,9,0,8,26,1836,452
7,19008,Bustamante,2653,PAN,986,770,3,1,7,2,199,1,0,14,4,1,627,32
8,19009,Cadereyta Jiménez,36779,IND,7579,9741,68,201,2463,185,147,42,29,141,273,200,14669,869
9,19010,El Carmen,7650,IND,1674,1986,25,376,43,115,29,10,4,17,11,11,3127,185
10,19011,Cerralvo,4266,PAN,2150,1333,2,0,2,3,8,0,0,2,0,1,674,81
11,19012,Ciénega de Flores,11972,IND,2106,3061,911,115,339,58,199,19,11,21,65,16,4644,360
12,19013,China,6368,PAN,1832,1311,4,10,31,7,639,8,7,2,231,142,1623,333
13,19014,Dr. Arroyo,20735,PRI,7093,10643,56,97,38,9,32,6,4,16,23,10,2038,564
14,19015,Dr. Coss,1763,PRI,620,826,1,48,2,1,23,0,2,1,4,0,200,35
15,19016,Dr. González,2013,IND,532,587,1,174,24,7,3,1,1,1,4,1,588,84
16,19017,Galeana,20207,PRI,3347,7601,51,146,69,15,705,13,17,20,50,55,6700,1314
17,19018,García,61292,IND,6691,14170,887,304,191,146,183,41,31,133,149,78,37207,995
18,19019,San Pedro Garza García,65324,IND,15094,7031,106,167,186,403,152,36,38,113,355,78,40534,976
19,19020,Gral. Bravo,3934,PAN,1537,1514,3,5,6,4,10,0,2,9,2,1,760,69
20,19021,Gral. Escobedo,128285,IND,21046,30585,649,1017,815,710,423,43,82,413,350,191,69203,2335
21,19022,Gral. Terán,7916,PRI,2234,2905,5,17,23,14,39,7,3,6,343,4,1952,324
22,19023,Gral. Treviño,1303,PAN,694,428,1,0,0,3,7,0,2,1,0,0,148,19
23,19024,Gral. Zaragoza,4146,PRI,589,1661,4,996,4,3,4,1,0,2,10,3,671,182
24,19025,Gral. Zuazua,14830,IND,3529,3873,112,86,74,30,42,13,3,72,32,58,6582,257
25,19026,Guadalupe,308863,IND,65509,67458,986,1273,1592,1566,1326,168,256,1323,1036,629,158514,6037
26,19027,Los Herreras,2010,PAN,830,781,1,0,4,0,16,2,1,0,2,0,330,28
27,19047,Hidalgo,8427,IND,1712,1928,166,30,81,409,45,12,8,66,33,148,3372,224
28,19028,Higueras,1111,PRI,387,406,2,3,0,2,5,0,0,0,20,0,263,19
29,19029,Hualahuises,4152,PRI,1313,1617,6,6,8,5,67,2,2,2,8,4,1013,88
30,19030,Iturbide,2515,IND,589,870,1,1,4,2,19,0,1,0,6,2,919,96
31,19031,Juárez,86315,IND,14813,23752,218,283,575,264,286,49,48,257,210,2176,40771,2176
32,19032,Lampazos de Naranjo,3420,PAN,2044,977,3,2,10,4,2,0,1,0,4,1,327,43
33,19033,Linares,35563,IND,10359,7967,88,75,194,61,2173,23,18,31,55,23,12289,1369
34,19034,Marín,2947,PRI,856,1086,7,3,5,7,24,2,91,4,5,2,803,50
35,19035,Melchor Ocampo,1107,PRI,250,396,1,8,3,0,163,0,2,0,1,1,244,35
36,19036,Mier y Noriega,4154,PRI,1476,2114,11,9,127,2,37,0,0,8,9,2,226,128
37,19037,Mina,3499,PRI,312,1349,22,74,364,6,14,5,0,5,10,6,1182,113
38,19038,Montemorelos,27643,IND,4582,8597,105,189,188,70,522,18,32,132,77,62,12124,762
39,19039,Monterrey,543865,IND,115708,114564,1621,6563,2274,3302,1540,251,419,1765,1590,1385,278901,12269
40,19040,Parás,1466,PAN,754,446,1,4,0,1,1,2,0,1,0,0,238,16
41,19041,Pesquería,14821,PRI,2272,5474,51,41,1531,61,37,9,9,26,17,204,4670,355
42,19042,Los Ramones,3200,PRI,974,1245,1,3,423,2,4,0,2,8,49,1,401,63
43,19043,Rayones,2813,PAN,1192,1182,5,1,3,1,1,1,1,3,2,1,375,39
44,19044,Sabinas Hidalgo,18064,PAN,6694,5182,58,38,165,23,74,8,7,64,38,3,5389,287
45,19045,Salinas Victoria,17177,PRI,4484,5643,1396,86,65,28,84,23,6,23,19,8,4743,512
46,19046,San Nicolás de los Garza,224920,IND,67768,31185,668,1131,1214,1446,814,112,158,763,590,611,113889,4212
47,19048,Santa Catarina,109633,IND,26052,17353,376,422,530,552,431,58,87,279,387,174,60578,2152
48,19049,Santiago,21541,IND,5694,5720,31,686,88,117,60,8,13,53,96,14,8468,436
49,19050,Vallecillo,1576,PRI,249,633,4,270,10,0,6,1,2,1,6,1,359,34
50,19051,Villaldama,2901,IND,770,590,395,18,7,2,85,2,0,3,2,0,865,107

In [61]:
resultados_g2015 = resultados_g2015[['ID','Municipio','Total','Ganador','IND']]
resultados_g2015.head()

      ID    Municipio  Total Ganador   IND
0  19001      Abasolo   1757     IND   597
1  19002   Agualeguas   2755     PAN   287
2  19003  Los Aldamas   1507     PRI    90
3  19004      Allende  14762     IND  5721
4  19005      Anáhuac   9528     PAN  1903

## Gubernatura 2021

In [43]:
gubernatura2021 = pd.read_csv("../../resources/data/CEENL - Resultados Electorales/CEENL-Gubernatura-2021.csv", skiprows=5, encoding="latin-1",
                              names = ['CLAVE_CASILLA','CLAVE_ACTA','ID_ESTADO','ESTADO','ID_MUNICIPIO','Municipio',
                                       'ID_DISTRITO_LOCAL','DISTRITO_LOCAL','SECCION','ID_CASILLA','TIPO_CASILLA',
                                       'EXT_CONTIGUA','UBICACION_CASILLA','TIPO_ACTA','TOTAL_BOLETAS_SOBRANTES',
                                       'TOTAL_PERSONAS_VOTARON','TOTAL_REP_PARTIDO_CI_VOTARON','TOTAL_VOTOS_SACADOS',
                                       'PAN','PRI','PRD','PVEM','PT','MC','MORENA','PANAL','PES','RSP','FXM',
                                       'C_PRI_PRD','C_PVEM_PT_MORENA_PANAL','C_PVEM_PT_MORENA','C_PVEM_PT_PANAL',
                                       'C_PVEM_MORENA_PANAL','C_PT_MORENA_PANAL','C_PVEM_PT','C_PVEM_MORENA',
                                       'C_PVEM_PANAL','C_PT_MORENA','C_PT_PANAL','C_MORENA_PANAL','NO_REGISTRADOS',
                                       'NULOS','TOTAL_VOTOS_ASENTADO','Total','LISTA_NOMINAL',
                                       'REPRESENTANTES_PP_CI','OBSERVACIONES','CONTABILIZADA','MECANISMOS_TRASLADO',
                                       'SHA','FECHA_HORA_ACOPIO','FECHA_HORA_CAPTURA','FECHA_HORA_VERIFICACION',
                                       'ORIGEN','DIGITALIZACION','TIPO_DOCUMENTO'])

print(gubernatura2021.shape)
gubernatura2021.head()

(7003, 57)

,CLAVE_CASILLA,CLAVE_ACTA,ID_ESTADO,ESTADO,ID_MUNICIPIO,Municipio,ID_DISTRITO_LOCAL,DISTRITO_LOCAL,SECCION,ID_CASILLA,...,OBSERVACIONES,CONTABILIZADA,MECANISMOS_TRASLADO,SHA,FECHA_HORA_ACOPIO,FECHA_HORA_CAPTURA,FECHA_HORA_VERIFICACION,ORIGEN,DIGITALIZACION,TIPO_DOCUMENTO
0,190001B0100,190001B01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,1,1,...,Por MAC,1,D,NaN,NaN,09/06/2021 09:33:55,NaN,NaN,NaN,-
1,190001C0100,190001C01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,1,1,...,Por MAC,1,D,NaN,NaN,09/06/2021 09:36:28,NaN,NaN,NaN,-
2,190002B0100,190002B01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,2,1,...,Por MAC,1,D,NaN,NaN,09/06/2021 09:39:13,NaN,NaN,NaN,-
3,190002C0100,190002C01002,19,NUEVO LEON,1,Abasolo,20,DISTRITO 20,2,1,...,Por MAC,1,D,NaN,NaN,09/06/2021 09:41:02,NaN,NaN,NaN,-
4,190003B0100,190003B01002,19,NUEVO LEON,2,Agualeguas,21,DISTRITO 21,3,1,...,Por MAC,1,D,NaN,NaN,09/06/2021 10:23:55,NaN,NaN,NaN,-

In [44]:
gubernatura2021.iloc[:,17:44].columns
gubernatura2021.iloc[:,18:45].sum(axis=0)

PAN                        392933.0
PRI                        583067.0
PRD                          8928.0
PVEM                        32684.0
PT                          29490.0
MC                         786918.0
MORENA                     212781.0
PANAL                       14671.0
PES                          7047.0
RSP                          6629.0
FXM                         13862.0
C_PRI_PRD                    5983.0
C_PVEM_PT_MORENA_PANAL       3971.0
C_PVEM_PT_MORENA             1317.0
C_PVEM_PT_PANAL               389.0
C_PVEM_MORENA_PANAL           545.0
C_PT_MORENA_PANAL             368.0
C_PVEM_PT                     518.0
C_PVEM_MORENA                1126.0
C_PVEM_PANAL                  305.0
C_PT_MORENA                  1662.0
C_PT_PANAL                    188.0
C_MORENA_PANAL                641.0
NO_REGISTRADOS                746.0
NULOS                       36503.0
TOTAL_VOTOS_ASENTADO            0.0
Total                     2143272.0
dtype: float64

In [45]:
votos_g2021 = gubernatura2021[['Municipio','Total', 'PAN', 'PRI', 'PRD', 'PVEM', 'PT', 'MC',
       'MORENA', 'PANAL', 'PES', 'RSP', 'FXM', 'NO_REGISTRADOS', 'NULOS']].groupby('Municipio').sum()

print(votos_g2021.shape)
votos_g2021.head()

(51, 14)

,Total,PAN,PRI,PRD,PVEM,PT,MC,MORENA,PANAL,PES,RSP,FXM,NO_REGISTRADOS,NULOS
Municipio,,,,,,,,,,,,,,
Abasolo,2014,483,255,18,232,71,763,102,20,20,9,17,1,20
Agualeguas,2898,1515,340,4,9,4,778,161,7,0,1,0,0,52
Allende,13165,2340,4810,51,141,156,4106,860,145,26,206,33,0,253
Anahuac,8860,1325,3979,29,99,77,1900,1046,50,70,18,26,0,214
Apodaca,220895,39757,58969,873,1756,2031,86520,22626,985,859,551,1520,74,3045

In [46]:
votos_g2021.rename({'PANAL': 'NA'}, axis=1, inplace=True)

In [47]:
ganadores_g2021 = votos_g2021.iloc[:,1:].idxmax(axis=1)
ganadores_g2021.to_list()[0:5]

['MC', 'PAN', 'PRI', 'PRI', 'MC']

In [48]:
ganadores_g2021.value_counts()

MC     22
PRI    15
PAN    12
PT      1
NA      1
dtype: int64

In [49]:
votos_g2021.insert(1, 'Ganador', ganadores_g2021)
print(votos_g2021.shape)
votos_g2021.head()

(51, 15)

,Total,Ganador,PAN,PRI,PRD,PVEM,PT,MC,MORENA,NA,PES,RSP,FXM,NO_REGISTRADOS,NULOS
Municipio,,,,,,,,,,,,,,,
Abasolo,2014,MC,483,255,18,232,71,763,102,20,20,9,17,1,20
Agualeguas,2898,PAN,1515,340,4,9,4,778,161,7,0,1,0,0,52
Allende,13165,PRI,2340,4810,51,141,156,4106,860,145,26,206,33,0,253
Anahuac,8860,PRI,1325,3979,29,99,77,1900,1046,50,70,18,26,0,214
Apodaca,220895,MC,39757,58969,873,1756,2031,86520,22626,985,859,551,1520,74,3045

In [50]:
resultados_g2021 = ID_Municipios_2018.merge(votos_g2021, on='Municipio')
print(resultados_g2021.shape)
resultados_g2021

(51, 17)

,ID,Municipio,Total,Ganador,PAN,PRI,PRD,PVEM,PT,MC,MORENA,NA,PES,RSP,FXM,NO_REGISTRADOS,NULOS
0,19001,Abasolo,2014,MC,483,255,18,232,71,763,102,20,20,9,17,1,20
1,19002,Agualeguas,2898,PAN,1515,340,4,9,4,778,161,7,0,1,0,0,52
2,19003,Los Aldamas,1365,MC,67,553,8,7,6,583,34,60,0,1,2,0,40
3,19004,Allende,13165,PRI,2340,4810,51,141,156,4106,860,145,26,206,33,0,253
4,19005,Anahuac,8860,PRI,1325,3979,29,99,77,1900,1046,50,70,18,26,0,214
5,19006,Apodaca,220895,MC,39757,58969,873,1756,2031,86520,22626,985,859,551,1520,74,3045
6,19007,Aramberri,10020,PRI,2847,4809,14,53,938,624,414,35,7,3,10,0,220
7,19008,Bustamante,2639,PAN,765,602,5,94,31,626,211,55,8,165,39,2,29
8,19009,Cadereyta Jimenez,38082,MC,7613,9104,253,2492,710,10540,4880,324,205,235,626,5,799
9,19010,El Carmen,12198,MC,2826,1993,68,942,405,3886,1207,94,36,26,92,2,251
10,19011,Cerralvo,4324,PAN,1910,641,10,20,30,548,989,22,11,16,11,0,103
11,19012,Cienega de Flores,15179,MC,4008,1885,116,1425,199,4858,1803,111,55,24,249,2,312
12,19013,China,6629,PRI,955,1881,40,115,69,1380,490,1158,90,8,10,0,209
13,19014,Dr. Arroyo,21632,PRI,1751,12320,25,122,184,1806,4476,152,44,132,68,0,481
14,19015,Dr. Coss,1785,PRI,172,710,5,22,7,219,61,461,2,17,0,0,35
15,19016,Dr. Gonzalez,2359,PRI,342,762,11,33,311,552,88,185,1,8,5,1,51
16,19017,Galeana,19609,PRI,3195,8563,41,3902,397,1789,759,159,16,15,29,4,606
17,19018,Garcia,72490,MC,12537,14076,522,1143,988,29460,9710,550,666,326,700,29,1349
18,19019,San Pedro Garza Garcia,73936,MC,9198,22150,305,369,212,37196,2721,178,128,69,301,46,849
19,19020,Gral. Bravo,3757,PAN,1375,1337,10,56,30,566,227,31,5,0,0,0,102
20,19021,Gral. Escobedo,137300,MC,23414,25096,708,2921,2412,53971,21711,1098,468,407,1011,62,2178
21,19022,Gral. Teran,7528,MC,497,2777,23,84,40,3102,365,105,24,242,33,0,197
22,19023,Gral. Trevino,1498,PAN,742,541,0,7,1,123,66,11,1,0,0,0,6
23,19024,Gral. Zaragoza,4171,PRI,444,1668,9,17,1519,257,67,12,3,9,2,0,78
24,19025,Gral. Zuazua,19887,MC,2998,3275,137,394,1183,7396,2730,134,229,625,187,11,338
25,19026,Guadalupe,289693,MC,52816,70275,1132,2899,2740,113767,32836,1590,1206,768,2010,127,5240
26,19027,Los Herreras,1565,PRI,223,529,9,364,5,215,61,100,0,1,2,0,49
27,19047,Hidalgo,7921,MC,1769,930,265,469,98,2935,620,303,80,93,151,3,179
28,19028,Higueras,1236,PAN,505,70,111,5,11,350,25,2,0,0,2,0,20
29,19029,Hualahuises,4291,PRI,687,2017,18,35,69,988,253,51,16,9,9,0,125
30,19030,Iturbide,2857,PRI,913,1340,2,27,42,316,146,6,0,1,1,0,52
31,19031,Juarez,101323,MC,15015,29136,385,1249,881,38949,11202,585,341,255,711,16,1574
32,19032,Lampazos de Naranjo,3612,PAN,2124,418,3,26,7,489,460,6,0,8,9,0,58
33,19033,Linares,31802,MC,7918,8252,185,359,504,8520,3893,580,95,151,134,10,975
34,19034,Marin,3207,MC,614,498,21,661,28,1054,179,39,2,2,12,0,76
35,19035,Melchor Ocampo,1458,NA,385,127,4,23,17,293,98,424,1,1,4,0,44
36,19036,Mier y Noriega,4865,PAN,1342,545,9,822,13,902,880,14,6,9,10,1,114
37,19037,Mina,3494,PRI,508,1388,9,656,10,719,83,21,7,5,9,0,70
38,19038,Montemorelos,25104,PRI,3278,8821,117,264,751,7090,3273,316,49,103,224,5,597
39,19039,Monterrey,542835,PRI,69240,200997,1978,3282,7646,199464,40577,1895,1205,842,2715,224,8718
40,19040,Paras,1667,PAN,764,418,6,12,8,339,70,10,2,2,3,0,32
41,19041,Pesqueria,23540,PAN,7705,3092,116,562,592,6833,3551,149,74,79,107,4,407
42,19042,Los Ramones,2964,PAN,1064,525,3,50,11,365,101,686,7,53,5,0,69
43,19043,Rayones,2434,PAN,1329,324,1,25,25,348,273,26,5,6,4,0,62
44,19044,Sabinas Hidalgo,16783,MC,5418,2242,48,769,132,6424,994,92,25,167,87,0,308
45,19045,Salinas Victoria,22673,MC,5349,4292,106,246,246,8884,2345,141,47,68,305,6,401
46,19046,San Nicolas de los Garza,207838,MC,62875,34771,570,1478,1665,78468,20534,742,498,386,1299,78,2950
47,19048,Santa Catarina,105549,MC,22731,19363,375,936,767,45428,10817,559,344,460,940,31,2043
48,19049,Santiago,25546,MC,4253,8766,153,339,614,8881,1555,178,58,38,130,2,446
49,19050,Vallecillo,1682,PT,179,542,14,19,582,239,39,4,4,2,5,0,35
50,19051,Villaldama,3113,MC,853,293,3,652,15,1109,112,10,1,7,3,0,42

In [62]:
resultados_g2021 = resultados_g2021[['ID','Municipio','Total','Ganador','MC']]
resultados_g2021.head()

      ID    Municipio  Total Ganador    MC
0  19001      Abasolo   2014      MC   763
1  19002   Agualeguas   2898     PAN   778
2  19003  Los Aldamas   1365      MC   583
3  19004      Allende  13165     PRI  4106
4  19005      Anahuac   8860     PRI  1900

## Superficie NL

In [5]:
superficie_NL = pd.read_csv("../../resources/data/Superficie/Superficie-NL.csv")
print(superficie_NL.shape)
superficie_NL.head()

(51, 3)

      ID    Municipio  Superficie
0  19001      Abasolo      44.603
1  19002   Agualeguas    1034.650
2  19003  Los Aldamas     645.242
3  19004      Allende     186.923
4  19005      Anáhuac    4303.610

## Export to JSON

In [7]:
# orient = "columns"
orient = "records"

In [64]:
ID_Municipios_2015.to_json("../output/id_municipios.json", orient=orient)

In [65]:
resultados_a2015.to_json("../output/resultados_a2015.json", orient=orient)
resultados_a2018.to_json("../output/resultados_a2018.json", orient=orient)
resultados_a2021.to_json("../output/resultados_a2021.json", orient=orient)

In [66]:
resultados_g2015.to_json("../output/resultados_g2015.json", orient=orient)
resultados_g2021.to_json("../output/resultados_g2021.json", orient=orient)

In [8]:
superficie_NL.to_json("../output/superficie_NL.json", orient=orient)

In [67]:
id_municipios_json = ID_Municipios_2015.to_json(orient=orient)
print(id_municipios_json[0])

[

## Store in MongoDB

In [56]:
STOP CODE HERE!!

SyntaxError: invalid syntax (<ipython-input-56-59a53f0aad35>, line 1)

In [ ]:
## Dependencies
import pymongo
import json

In [ ]:
## Setup Database connection (MongoDB)
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

## Define database in Mongo
db = client.ElectionsDB

In [ ]:
## Build dictionaries
id_municipios_dict = ID_Municipios_2015.to_dict('records')
resultados_a2015_dict = resultados_a2015.to_dict('records')
resultados_a2018_dict = resultados_a2018.to_dict('records')
resultados_a2021_dict = resultados_a2021.to_dict('records')
resultados_g2015_dict = resultados_g2015.to_dict('records')
resultados_g2021_dict = resultados_g2021.to_dict('records')

In [ ]:
## Add to database
db.id_municipios.insert_many(id_municipios_dict)
db.a2015.insert_many(resultados_a2015_dict)
db.a2018.insert_many(resultados_a2018_dict)
db.a2021.insert_many(resultados_a2021_dict)
db.g2015.insert_many(resultados_g2015_dict)
db.g2021.insert_many(resultados_g2021_dict)