In [1]:
import pandas as pd

In [2]:
coordinates_path = "../../resources/data/Coordenadas/lat_lon.csv"

In [3]:
coordinates = pd.read_csv(coordinates_path, encoding='latin-1')
coordinates.head()

   LATITUD  LONGITUD     ID
0  25.9296 -100.4209  19001
1  26.4300  -99.5700  19002
2  26.0354  -99.2891  19003
3  25.2841 -100.0260  19004
4  27.3900 -100.3200  19005

In [4]:
first_path = "../../resources/data/Relacion ID-Municipios/ID-Municipios.csv"

In [5]:
id_municipality = pd.read_csv(first_path, encoding='latin-1')
id_municipality

       ID                 Municipio
0   19001                   Abasolo
1   19002                Agualeguas
2   19003               Los Aldamas
3   19004                   Allende
4   19005                   Anáhuac
5   19006                   Apodaca
6   19007                 Aramberri
7   19008                Bustamante
8   19009         Cadereyta Jiménez
9   19010                 El Carmen
10  19011                  Cerralvo
11  19012         Ciénega de Flores
12  19013                     China
13  19014                Dr. Arroyo
14  19015                  Dr. Coss
15  19016              Dr. González
16  19017                   Galeana
17  19018                    García
18  19019    San Pedro Garza García
19  19020               Gral. Bravo
20  19021            Gral. Escobedo
21  19022               Gral. Terán
22  19023             Gral. Treviño
23  19024            Gral. Zaragoza
24  19025              Gral. Zuazua
25  19026                 Guadalupe
26  19027              Los Herreras
27  19047                   Hidalgo
28  19028                  Higueras
29  19029               Hualahuises
30  19030                  Iturbide
31  19031                    Juárez
32  19032       Lampazos de Naranjo
33  19033                   Linares
34  19034                     Marín
35  19035            Melchor Ocampo
36  19036            Mier y Noriega
37  19037                      Mina
38  19038              Montemorelos
39  19039                 Monterrey
40  19040                     Parás
41  19041                 Pesquería
42  19042               Los Ramones
43  19043                   Rayones
44  19044           Sabinas Hidalgo
45  19045          Salinas Victoria
46  19046  San Nicolás de los Garza
47  19048            Santa Catarina
48  19049                  Santiago
49  19050                Vallecillo
50  19051                Villaldama

In [6]:
approved_df = pd.merge(id_municipality, coordinates, on = "ID", how = "inner")
approved_df

       ID                 Municipio  LATITUD  LONGITUD
0   19001                   Abasolo  25.9296 -100.4209
1   19002                Agualeguas  26.4300  -99.5700
2   19003               Los Aldamas  26.0354  -99.2891
3   19004                   Allende  25.2841 -100.0260
4   19005                   Anáhuac  27.3900 -100.3200
5   19006                   Apodaca  25.7861 -100.2485
6   19007                 Aramberri  24.3100  -99.7400
7   19008                Bustamante  26.5700 -100.5500
8   19009         Cadereyta Jiménez  25.5880 -100.0062
9   19010                 El Carmen  25.9404 -100.3671
10  19011                  Cerralvo  26.3000  -99.6100
11  19012         Ciénega de Flores  25.9574 -100.2121
12  19013                     China  25.6700  -99.3900
13  19014                Dr. Arroyo  23.6500 -100.3500
14  19015                  Dr. Coss  25.8000  -99.3600
15  19016              Dr. González  25.7600  -99.8100
16  19017                   Galeana  24.7400 -100.2900
17  19018                    García  25.8044 -100.6015
18  19019    San Pedro Garza García  25.6525 -100.3909
19  19020               Gral. Bravo  25.7200  -99.3500
20  19021            Gral. Escobedo  25.8032 -100.3117
21  19022               Gral. Terán  25.2576  -99.6862
22  19023             Gral. Treviño  26.3800  -99.5400
23  19024            Gral. Zaragoza  23.8300  -99.7100
24  19025              Gral. Zuazua  25.8869 -100.1209
25  19026                 Guadalupe  25.6692 -100.2241
26  19027              Los Herreras  25.7900  -99.4900
27  19047                   Hidalgo  25.9699 -100.4634
28  19028                  Higueras  25.8200 -100.2500
29  19029               Hualahuises  24.7800  -99.6500
30  19030                  Iturbide  24.7263  -99.9066
31  19031                    Juárez  25.6476 -100.1097
32  19032       Lampazos de Naranjo  27.2600 -100.5500
33  19033                   Linares  24.7600  -99.5900
34  19034                     Marín  25.8778 -100.0316
35  19035            Melchor Ocampo  26.2800  -99.5700
36  19036            Mier y Noriega  23.5000 -100.3200
37  19037                      Mina  26.2500 -100.5600
38  19038              Montemorelos  25.1836  -99.8366
39  19039                 Monterrey  25.6914 -100.3299
40  19040                     Parás  26.5400  -99.5600
41  19041                 Pesquería  25.7100 -100.2800
42  19042               Los Ramones  25.6600  -99.6200
43  19043                   Rayones  25.2600 -100.2900
44  19044           Sabinas Hidalgo  26.5024 -100.1846
45  19045          Salinas Victoria  25.9732 -100.2951
46  19046  San Nicolás de los Garza  25.7348 -100.2809
47  19048            Santa Catarina  25.6500 -100.5200
48  19049                  Santiago  25.3781 -100.1927
49  19050                Vallecillo  26.6400  -99.8400
50  19051                Villaldama  26.4971 -100.4318

In [7]:
approved_df.to_csv("../output/coordinates.csv", index = True)

In [8]:
approved_df.to_json("../output/coordinatesr.js", orient = "records")

In [9]:
approved_df.to_json("../output/coordinatesc.js", orient = "columns")